- name: "Install generic packages that do not have configs"
  hosts: localhost
  tasks:
    - name: Install bat, btop, firefox, fzf, lsd, stow 
      become: true
      pacman:
        name:
          - bat
          - btop
          - firefox
          - fzf
          - lsd
          - papirus-icon-theme
          - stow
          - ttf-firacode-nerd
          - wl-clipboard
        state: present
        update_cache: yes

- import_playbook: git/playbook.yml
- import_playbook: zsh/playbook.yml
- import_playbook: wezterm/playbook.yml
- import_playbook: nvim/playbook.yml
