- name: "Install generic packages that do not have configs"
  hosts: localhost
  tasks:
    - name: Install bat, btop, firefox, fzf, lsd, stow 
      become: true
      pacman:
        name:
          - bat
          - btop
          - firefox
          - fzf
          - lsd
          - stow
        state: present
        update_cache: yes

- import_playbook: git/git-playbook.yml
- import_playbook: zsh/zsh-playbook.yml
- import_playbook: wezterm/wezterm-playbook.yml
- import_playbook: nvim/nvim-playbook.yml
