# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts

format = """
$username\
$hostname\
$localip\
$sh1v1\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character\
"""

[directory]
truncation_length = 50

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
style= "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$renamed$deleted)](white) ($staged  )($ahead_behind  )($stashed)]($style)"
style = "bright-black"
ahead = '[🡑](white)·${count}'
behind = '[🡓](white)·${count}'
diverged = '[🡙](white)·${count}'
conflicted = "​"
untracked = "​"
modified = "​"
staged = "[](white)·${count}"
renamed = "​"
deleted = "​"
stashed = "[](white)·${count}"
